- Corsair K70 MK2:
    url: https://www.amazon.fr/Corsair-RAPIDFIRE-M%C3%A9canique-R%C3%A9tro-%C3%89clairage-Multicolore/dp/B07HX99ZL6?ref_=ast_sto_dp&th=1
    current_price: 188.99
- Chaise SIHOO:
    url: https://www.amazon.fr/SIHOO-Ergonomique-Ordinateur-Protection-Appui-t%C3%AAte/dp/B07GNDDNMW/ref=pd_vtp_196_1/262-6129439-6376061?_encoding=UTF8&pd_rd_i=B07GNDDNMW&pd_rd_r=f19c9250-8b8f-4c70-b013-a66eb827b89f&pd_rd_w=j7Cq2&pd_rd_wg=BjFQq&pf_rd_p=d5223afe-1e0c-4a36-b13d-30661b0f79b3&pf_rd_r=ZS1S6W4AJ362QX5PM0HF&psc=1&refRID=ZS1S6W4AJ362QX5PM0HF
    current_price: 199.99

